# -*- coding: utf-8 -*-
"""RL Finance research paper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/111_gK156FScQu7ARE6hcnJn3too6CFGo
"""

!pip install gym-anytrading
!pip install stable-baselines3

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
#Stable Baseline3 for RL
from stable_baselines3 import PPO , DQN
from stable_baselines3.common.vec_env import DummyVecEnv
import gym
import gym_anytrading
#Computing Sharpe ratio
from gym_anytrading.envs import StocksEnv
#Evaluation metrics
#Computing Sharpe ratio
def sharpe_ratio(returns, risk_free= 0.0, annual_factor=252):
  excess_ret = returns - risk_free
  return np.mean(excess_ret) / (np.std(excess_ret) + 1e-9) * np.sqrt(annual_factor)
#Computing Maximum Drawdown
def max_drawdown(equity_curve):
    roll_max= np.maximum.accumulate(equity_curve)
    drawdown= (equity_curve-roll_max)/ roll_max
    return drawdown.min()

from dataclasses import dataclass

@dataclass
class RegimeSplit:
    """
    Defines regime-aware time slices for Train / Validation / Test.
    """
    train_start: str = "2012-01-01"
    train_end:   str = "2019-12-31"
    val_start:   str = "2020-01-01"
    val_end:     str = "2021-12-31"
    test_start:  str = "2022-01-01"
    test_end:    str = "2024-01-01"

#Using RegimeSplit class for data slicing
regimes=RegimeSplit()
df = yf.download("AAPL", regimes.train_start, regimes.test_end)
def slice_df(df, start, end):
   return df.query("@start <= Date < @end").reset_index(drop=True)
df_train = slice_df(df, regimes.train_start, regimes.train_end)
df_val = slice_df(df, regimes.val_start, regimes.val_end)
df_test = slice_df(df, regimes.test_start, regimes.test_end)
print("train:", df_train)
print("val:", df_val)
print("test:", df_test)

df.head()

#Plot showing the close price during training period
plt.figure(figsize=(12, 6))
plt.plot(df_train['Close'])
plt.title('AAPL Close Price - Training Data')
plt.xlabel('Time')
plt.ylabel('Close Price')
plt.show()
# This plot shows the closing price of AAPL during the training period.

